version: "3"
services:
  python:
    container_name: python
    image: test-python
    ports:
      - 5000:5000
    depends_on:
      - mountebank
      - mysql
    environment:
      - PEOPLE_URL=http://mountebank:5050
      - PLANETS_URL=http://mountebank:5051
      - STARSHIP_URL=http://mountebank:5052

  mountebank:
    container_name: mountebank
    image: test-mountebank
    volumes:
      - ./testEnv/imposters:/imposters
    ports:
      - 5050:5050
      - 5051:5051
      - 5052:5052

  mysql:
    container_name: mysql
    image: test-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: baris
      MYSQL_PASSWORD: 1
      MYSQL_DATABASE: StarWarsDB
      LANG: C-UTF-8

  swagger:
    image: swaggerapi/swagger-ui
    expose:
      - 8080
    ports:
      - 8090:8080
    environment:
      SWAGGER_JSON: /spec/swagger.json
    volumes:
      - ./swagger:/spec
